### ISSUE TITLE
Allow for multiple cleanup scripts

### ISSUE THREAD

**Issue by gr2m** [boennemann/clean-script#1]
let's say I have this

```
clean-script '(mybackgroundtask & echo $! >> test.pid) && npm test' 'cat test.pid | xargs kill && rm test.pid'
```

Problem here is that `xargs kill` might fail, and the `rm test.pid` would not be executed. This can be solved with clean-script inception, but it would be very nice to have a shortcut for such cases like this

```
clean-script '<main script>' '<cleanup1>' '<cleanup2>'
```

**Comment by boennemann** [comment]
https://github.com/boennemann/clean-script/commit/74f920b129d57f050ab4833075471f7bf8a27535

**Comment by gr2m** [comment]
you're the best, thanks :smile_cat:
